name = "Muscle"
uuid = "21fe5c4b-a943-414d-bf3e-516f24900631"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es> and contributors"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[extensions]
MuscleChainRulesCoreExt = "ChainRulesCore"
MuscleDaggerExt = "Dagger"
MuscleReactantExt = "Reactant"

[compat]
ChainRulesCore = "1.0"
Dagger = "0.18"
LinearAlgebra = "1.9"
OMEinsum = "0.8"
Reactant = "0.1"
StaticArrays = "1"
julia = "1.9"
