name = "Muscle"
uuid = "21fe5c4b-a943-414d-bf3e-516f24900631"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es> and contributors"]
version = "0.3.18"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
EinExprs = "b1794770-133b-4de1-afb4-526377e9f4c5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
QuantumTags = "2406e0f5-9e5e-4424-966e-8bc9c78b228f"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"
cuTENSOR = "011b41b2-24ef-40a8-b3eb-fa098493e9e1"
cuTensorNet = "448d79b3-4b49-4e06-a5ea-00c62c0dc3db"

[extensions]
MuscleCUDAExt = ["CUDA", "cuTENSOR"]
MuscleChainRulesCoreExt = "ChainRulesCore"
MuscleDaggerExt = "Dagger"
MuscleITensorsExt = "ITensors"
MuscleOMEinsumExt = "OMEinsum"
MuscleQuantumTagsExt = "QuantumTags"
MuscleReactantExt = "Reactant"
MuscleStridedExt = ["Strided", "StridedViews"]
MusclecuTensorNetExt = ["CUDA", "cuTensorNet"]

[compat]
Adapt = "4"
ArgCheck = "2.5.0"
CUDA = "5.7.0"
ChainRulesCore = "1.0"
Dagger = "0.18"
EinExprs = "0.6.8, 0.7"
ITensors = "0.9"
LinearAlgebra = "1.10"
OMEinsum = "0.8"
PrecompileTools = "1.2.1"
QuantumTags = "0.1.4, 0.2, 0.3"
Reactant = "0.2.134"
ScopedValues = "1.3.0"
StaticArrays = "1"
Strided = "2.3.0"
StridedViews = "0.4.1"
VectorInterface = "0.5.0"
cuTENSOR = "2.2.2"
cuTensorNet = "1.3.2"
julia = "1.10"
