name = "Muscle"
uuid = "21fe5c4b-a943-414d-bf3e-516f24900631"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[extensions]
MuscleReactantExt = "Reactant"

[compat]
Reactant = "0.1"
StaticArrays = "1"
julia = "1.8"
