name: CI
on:
  push:
    branches:
      - master
    tags: ['*']
    paths:
      - '**.toml'
      - '**.jl'
      - 'docs/*'
  pull_request:
    paths:
      - '**.toml'
      - '**.jl'
      - 'docs/*'
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} / downgrade = ${{ matrix.downgrade }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
        arch:
          - x64
        downgrade: ['false']
        # include:
        #   - version: '1.10'
        #     test_group: unit
        #     os: ubuntu-latest
        #     arch: x64
        #     downgrade: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          include-all-prereleases: true
      - uses: julia-actions/cache@v1
      - name: Add Julia registries
        run: |
          using Pkg
          pkg"registry add https://github.com/bsc-quantic/Registry.git"
          pkg"registry add General"
        shell: julia --color=yes {0}
      - uses: julia-actions/julia-downgrade-compat@v1
        if: ${{ matrix.downgrade == 'true' }}
        with:
          skip: 'Compat, LinearAlgebra'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          MUSCLE_TEST_REACTANT: 'true'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
